name: test_and_lint
on: [push]
jobs:
  test_latest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: install protoc
        run: sudo bash .devcontainer/install-protoc.sh

      - run: zig build
      - run: zig build test

  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install protoc
        run: sudo bash .devcontainer/install-protoc.sh
      - run: zig build
      - run: zig build test
      - run: zig build bootstrap
      - run: zig build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src/protobuf.zig